blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/vanman2024/recruitment_ops/wiki
    about: Check our documentation for answers
  - name: Discussions
    url: https://github.com/vanman2024/recruitment_ops/discussions
    about: Ask questions and discuss ideas
  - name: Security Issue
    url: mailto:security@example.com
    about: Please report security vulnerabilities via email