name: Task
description: Create a task for development work
title: "[Task]: "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create development tasks for the Recruitment Operations system.

  - type: dropdown
    id: task_type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Implementation
        - Refactoring
        - Testing
        - Documentation
        - Research
        - Configuration
        - Deployment
        - Maintenance
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this task involve?
      multiple: true
      options:
        - CATS Integration
        - Candidate Processing
        - Job Matching (AI)
        - Batch Processing
        - Webhook Server
        - Slack Notifications
        - Configuration
        - Tests
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Clear description of what needs to be done
      placeholder: |
        As a developer, I need to...
        So that...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be completed for this task to be done?
      placeholder: |
        - [ ] Unit tests pass
        - [ ] Code reviewed
        - [ ] Documentation updated
        - [ ] Integration tests pass
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details
      description: Any technical specifications or requirements
      placeholder: |
        - Files to modify:
        - APIs to integrate:
        - Dependencies:

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How big is this task?
      options:
        - XS (< 2 hours)
        - S (2-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (> 1 week)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Task priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: Links to related issues or PRs this depends on
      placeholder: "Depends on #123, Blocked by #456"

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information